Publish docker image using semantic versioning

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -54,5 +54,96 @@ jobs:
         run: |
           echo "The built jar is ${{ steps.get-jar.outputs.jar_name }}"
       - run: mkdir staging && tar zcvf artifact.tgz $(find . -name "${{ steps.get-jar.outputs.jar_name }}" -exec dirname {} \;)
-      - run: ls
+      - run: cp artifact.tgz staging
       - run: cp ci/Dockerfile staging
+      - uses: actions/upload-artifact@v4
+        with:
+          name: artifact
+          path: staging
+  publish:
+    name: Publish docker image to Docker Hub
+    runs-on: ubuntu-latest
+    needs:
+      - build
+    outputs:
+      docker-image: ${{ steps.meta.outputs.tags }}
+    env:
+      CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
+      CONTAINER_REGISTRY_USERNAME: ${{ vars.DOCKER_HUB_USERNAME }}
+      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
+      NAMESPACE: ${{ vars.DOCKER_HUB_USERNAME }}
+      IMAGE_NAME: ${{ vars.DOCKER_HUB_REPOSITORY }}
+    steps:
+      - name: Validate required variables
+        run: |
+          if [ -z "${{ vars.DOCKER_HUB_REPOSITORY }}" ]; then
+            echo "Error: DOCKER_HUB_REPOSITORY is not set."
+            exit 1
+          fi
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: artifact
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: artifact
+      - name: Login to container repository
+        if: github.event_name != 'pull_request'
+        uses: docker/login-action@v3
+        with:
+          registry: ${{ env.CONTAINER_REGISTRY }}
+          username: ${{ env.CONTAINER_REGISTRY_USERNAME }}
+          password: ${{ env.CONTAINER_REGISTRY_PASSWORD }}
+      - name: Extract metadata (tags, labels) for Docker
+        id: meta
+        uses: docker/metadata-action@v5
+        with:
+          images: |
+            ${{ env.CONTAINER_REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}
+          tags: |
+#            type=semver,pattern={{version}},value=${{ inputs.version }}
+            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.version }}
+            type=semver,pattern={{major}},value=${{ inputs.version }}
+            type=ref,event=branch,suffix=-{{ sha }}
+            type=ref,event=pr
+            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
+            type=semver,pattern={{version}},value=${{ inputs.tag || github.ref_name }}
+      - name: Build and push Docker Image
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          file: ./Dockerfile
+          push: ${{ github.event_name != 'pull_request' }}
+          tags: ${{ steps.meta.outputs.tags }}
+          labels: ${{ steps.meta.outputs.labels }}
+          build-args: |
+            JAR_FILE=${{ needs.build.outputs.jar_file_name }}
+  deploy:
+    name: Deploy to Kubernetes
+    runs-on: ubuntu-latest
+    needs: [ publish ]
+    env:
+      NAMESPACE: example
+      REPLICAS: 2
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Set the Kubernetes context
+        uses: azure/k8s-set-context@v4
+        with:
+          method: service-account
+          k8s-url: ${{ secrets.KUBERNETES_URL }}
+          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
+      - name: Deploy to the Kubernetes cluster
+        uses: azure/k8s-deploy@v5
+        with:
+          strategy: basic
+          action: deploy
+          namespace: ${{ env.NAMESPACE }}
+          manifests: |
+            manifests/deployment.yaml
+            manifests/service.yaml
+            manifests/ingress.yaml
+          images: |
+            ${{ needs.publish.outputs.docker-image }}
